### ISSUE TITLE
Confirm yaml anchors can be extended

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-configuration#19]
Currently in the example config, the following section exists:

https://github.com/open-telemetry/opentelemetry-configuration/blob/362b23ec9bb61537e6479a9546d7e8f8a388ec81/kitchen-sink-example.yaml#L95-L103

This configuration is intended to pull in the `otlp-exporter` configuration as an anchor, then add `temporality_preference` and `default_histogram_aggregation` to its configuration. However, I think those are currently applied to the `exporter` configuration and not the `otlp-exporter`.

Is this ok? I was under the impression that we would want to apply those to the otlp exporter block, rather than the exporter block.

**Comment by jack-berg** [comment]
I believe that should be fine.

**Comment by jack-berg** [comment]
In java we upgraded to the successor of a popular yaml parsing library and support for the merge symbol ("<<:") was removed! Based on comments on issues in the library, it sounds like supporting merge is optional in YAML 1.2. 

Here's an [comment](https://github.com/open-telemetry/opentelemetry-java/pull/5687/commits/854b537c97d7e547bfedd886cfe69f0acc5325ff#r1289161920) where I talk about this a bit more.

**Comment by jack-berg** [comment]
- We can't rely on YAML parsers supporting the `<<:` syntax, and shouldn't make modeling decision based on the assumption that the syntax is supported
- Should do more research to see if YAML 1.2 added support for some alternative
- Our schema currently requires users to copy / paste OTLP exporter configuration, which YAML anchors helps reduce. Is it acceptable to go stable with a configuration model which requires repeats OTLP exporter configuration for each signal? **Probably yes. Can add support for an improved syntax in a later version.**

If there is no YAML 1.2 replacement for the `<<:` syntax, let's delete the anchors example.

**Comment by jack-berg** [comment]
This [document](https://ktomk.github.io/writing/yaml-anchor-alias-and-merge-key.html) provides a good summary of the the merge operator (i.e. `<<:`). They have been deprecated without replacement in YAML 1.1, although there is some hints that future YAML version 1.3 may include some alternative. For now, we should delete the `anchors.yaml` example since declarative configuration requires [YAML 1.2](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/data-model.md#yaml-file-format).
